In [1]:
import pandas as pd
import numpy as np

In [2]:
attendance = pd.read_excel("../data/Attendance_Juli.xlsx")

for div in sorted(attendance["Division"].dropna().unique()):
    print(div)

Asset Management Division
Business Process & Innovation Division
Customer Care & Service Assurance Management Division
Enterprise Sales Division
Finance, Accounting, Tax Division
Human Capital & General Affairs Division
IT Business Application & Project Management Division
IT Infrastructure & Data Service Division
Internal Audit & Risk Management Division
Network Development Division
Network Operation Division
Procurement & Logistic Division
Product & Business Solution Division
Regional Sales Division
Service Operation Division

In [3]:
attendance = attendance[attendance["Division"] == "Asset Management Division"].copy()

In [34]:
attendance_work = attendance[
    [
        "No",
        "Date",
        "Employee No",
        "Employee Name",
        "Division",
        "Attendance Status",
        "Time In",
        "Time Out",
        "Late In",
        "Remarks",
    ]
].copy()

In [23]:
type(attendance)

pandas.DataFrame

In [24]:
attendance.info()

<class 'pandas.DataFrame'>
Index: 291 entries, 5302 to 33799
Data columns (total 44 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   No                                  291 non-null    float64
 1   Date                                291 non-null    datetime64[us]
 2   Employee No                         291 non-null    str
 3   Employee Name                       291 non-null    str
 4   Division                            291 non-null    str
 5   Job Title                           291 non-null    str
 6   Company                             291 non-null    str
 7   Attendance Status                   291 non-null    str
 8   Shift                               291 non-null    str
 9   Date In                             178 non-null    datetime64[us]
 10  Time In                             178 non-null    str
 11  Date Out                            172 non-null    datetime64[us]
 12  Time Out                            172 non-null    str
 13  Actual Working Hours (HH:mm)        183 non-null    str
 14  Data Source                         183 non-null    str
 15  Remarks                             291 non-null    str
 16  Lock Status                         291 non-null    float64
 17  Attendance Data                     178 non-null    str
 18  Unnamed: 18                         168 non-null    str
 19  Overtime (Minute)                   291 non-null    object
 20  Unnamed: 20                         291 non-null    object
 21  Unnamed: 21                         291 non-null    object
 22  Unnamed: 22                         291 non-null    object
 23  Unnamed: 23                         291 non-null    object
 24  Overtime Real Time (Minute)         291 non-null    object
 25  Unnamed: 25                         291 non-null    object
 26  Unnamed: 26                         291 non-null    object
 27  Unnamed: 27                         291 non-null    object
 28  Break Duration (Minute)             0 non-null      str
 29  Unnamed: 29                         0 non-null      str
 30  Late Tolerance                      291 non-null    float64
 31  Early Out Tolerance                 291 non-null    float64
 32  Payroll Group                       291 non-null    str
 33  Period                              291 non-null    str
 34  Late In                             291 non-null    float64
 35  Late & Early Out Duration (Minute)  291 non-null    object
 36  Unnamed: 36                         291 non-null    object
 37  Break Duration Hour (Minute)        291 non-null    float64
 38  Attendance Allowance                291 non-null    object
 39  Unnamed: 39                         291 non-null    object
 40  Unnamed: 40                         291 non-null    object
 41  Unnamed: 41                         291 non-null    object
 42  Unnamed: 42                         291 non-null    object
 43  Unnamed: 43                         291 non-null    object
dtypes: datetime64[us](3), float64(6), object(17), str(18)
memory usage: 102.3+ KB

In [7]:
#count day

pattern = "Present|Business Trip|Present Off|Absent|Leave"

attendance_work["Count Day"] = (
    attendance_work["Attendance Status"]
    .fillna("")
    .str.contains(pattern, case=False, regex=True)
    .astype(int)
)

In [8]:
#clock in

attendance_work["Clock In"] = (
    attendance_work["Time In"].notna()
    |
    attendance_work["Attendance Status"]
        .fillna("")
        .str.contains("Leave", case=False)
).astype(int)

In [9]:
#clock out

attendance_work["Clock Out"] = (
    attendance_work["Time Out"].notna()
    |
    attendance_work["Attendance Status"]
        .fillna("")
        .str.contains("Leave", case=False)
).astype(int)

In [10]:
#late

attendance_work["Late"] = (
    attendance_work["Late In"] > 0
).astype(int)

In [11]:
summary = (
    attendance_work
    .groupby(["Employee No", "Employee Name"])
    .agg(
        Division=("Division", "first"),
        Count_Day=("Count Day", "sum"),
        Clock_In=("Clock In", "sum"),
        Clock_Out=("Clock Out", "sum"),
        Late=("Late", "sum")
    )
    .reset_index()
)

In [12]:
summary["C.In"] = np.where(
    summary["Count_Day"] == 0,
    0,
    summary["Clock_In"] / summary["Count_Day"]
)

summary["C.Out"] = np.where(
    summary["Count_Day"] == 0,
    0,
    summary["Clock_Out"] / summary["Count_Day"]
)

summary["Late"] = np.where(
    summary["Count_Day"] == 0,
    0,
    summary["Late"] / summary["Count_Day"]
)

In [13]:
summary["C.In"] = summary["C.In"].map("{:.0%}".format)
summary["C.Out"] = summary["C.Out"].map("{:.0%}".format)
summary["Late"] = summary["Late"].map("{:.0%}".format)

In [15]:
attendance = pd.read_excel("../data/Attendance_Juli.xlsx")

print("Total data :", len(attendance))

attendance["Division"] = attendance["Division"].astype(str).str.strip()

attendance = attendance[
    attendance["Division"] == "Asset Management Division"
].copy()

print("Setelah filter :", len(attendance))

Total data : 33946
Setelah filter : 291

In [16]:
print(attendance.shape)

(291, 44)

In [17]:
print(summary.shape)
display(summary.head(20))

(0, 9)

Empty DataFrame
Columns: [Employee No, Employee Name, Division, Count_Day, Clock_In, Clock_Out, Late, C.In, C.Out]
Index: []

In [18]:
print(attendance_work.shape)

(0, 14)

In [19]:
attendance_work.head()

Empty DataFrame
Columns: [No, Date, Employee No, Employee Name, Division, Attendance Status, Time In, Time Out, Late In, Remarks, Count Day, Clock In, Clock Out, Late]
Index: []

In [20]:
attendance.columns.tolist()

['No',
 'Date',
 'Employee No',
 'Employee Name',
 'Division',
 'Job Title',
 'Company',
 'Attendance Status',
 'Shift',
 'Date In',
 'Time In',
 'Date Out',
 'Time Out',
 'Actual Working Hours (HH:mm)',
 'Data Source',
 'Remarks',
 'Lock Status',
 'Attendance Data',
 'Unnamed: 18',
 'Overtime (Minute)',
 'Unnamed: 20',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23',
 'Overtime Real Time (Minute)',
 'Unnamed: 25',
 'Unnamed: 26',
 'Unnamed: 27',
 'Break Duration (Minute)',
 'Unnamed: 29',
 'Late Tolerance',
 'Early Out Tolerance',
 'Payroll Group',
 'Period',
 'Late In',
 'Late & Early Out Duration (Minute)',
 'Unnamed: 36',
 'Break Duration Hour (Minute)',
 'Attendance Allowance',
 'Unnamed: 39',
 'Unnamed: 40',
 'Unnamed: 41',
 'Unnamed: 42',
 'Unnamed: 43']

In [21]:
import pandas as pd

# Selalu baca ulang file dari awal
attendance = pd.read_excel("../data/Attendance_Juli.xlsx")

print("Awal :", attendance.shape)

attendance["Division"] = attendance["Division"].astype(str).str.strip()

attendance = attendance[
    attendance["Division"] == "Asset Management Division"
].copy()

print("Sesudah filter :", attendance.shape)

Awal : (33946, 44)
Sesudah filter : (291, 44)

In [22]:
import pandas as pd

# Membaca file
attendance = pd.read_excel("../data/Attendance_Juli.xlsx")

# Membersihkan spasi pada nama divisi
attendance["Division"] = attendance["Division"].astype(str).str.strip()

# Mengambil semua divisi yang mengandung kata "Asset"
attendance = attendance[
    attendance["Division"].str.contains("Asset", case=False, na=False)
].copy()

print("Attendance:", attendance.shape)

# Memilih kolom yang dibutuhkan
attendance_work = attendance[
    [
        "No",
        "Date",
        "Employee No",
        "Employee Name",
        "Division",
        "Attendance Status",
        "Time In",
        "Time Out",
        "Late In",
        "Remarks"
    ]
].copy()

print("Attendance Work:", attendance_work.shape)

display(attendance_work.head(300))

Attendance: (291, 44)
Attendance Work: (291, 10)

,No,Date,Employee No,Employee Name,Division,Attendance Status,Time In,Time Out,Late In,Remarks
5302,5302.0,2026-07-01,E2001548,Heri Susetyo,Asset Management Division,Present,07:53,17:25,0.0,
5303,5303.0,2026-07-02,E2001548,Heri Susetyo,Asset Management Division,"Present, Abnormal, Late In",08:01,NaN,1.0,Time IN exists but there is no time OUT
5304,5304.0,2026-07-03,E2001548,Heri Susetyo,Asset Management Division,Present,08:00,18:08,0.0,
5305,5305.0,2026-07-04,E2001548,Heri Susetyo,Asset Management Division,Off,NaN,NaN,0.0,
5306,5306.0,2026-07-05,E2001548,Heri Susetyo,Asset Management Division,Off,NaN,NaN,0.0,
...,...,...,...,...,...,...,...,...,...,...
33795,33795.0,2026-07-27,X26011135,Indah Sari Aritonang,Asset Management Division,"Present, Late In",08:03,17:14,3.0,
33796,33796.0,2026-07-28,X26011135,Indah Sari Aritonang,Asset Management Division,Present,07:54,17:17,0.0,
33797,33797.0,2026-07-29,X26011135,Indah Sari Aritonang,Asset Management Division,Present,07:45,17:09,0.0,
33798,33798.0,2026-07-30,X26011135,Indah Sari Aritonang,Asset Management Division,Present,07:59,17:08,0.0,
33799,33799.0,2026-07-31,X26011135,Indah Sari Aritonang,Asset Management Division,"Present, Late In",08:03,17:43,3.0,

In [25]:
#pd.set_option("display.max_rows", None)
#display(attendance_work)

In [32]:
print(attendance_work.columns.tolist())

['No', 'Date', 'Employee No', 'Employee Name', 'Division', 'Attendance Status', 'Time In', 'Time Out', 'Late In', 'Remarks']

In [31]:
summary = (
    attendance_work
    .groupby(["Employee No", "Employee Name"])
    .agg(
        Division=("Division","first"),
        Count_Day=("Count Day","sum"),
        Clock_In=("Time In","sum"),
        Clock_Out=("Time Out","sum"),
        Late_Count=("Late In","sum")
    )
    .reset_index()
)

summary["C.In"] = summary["Clock_In"] / summary["Count_Day"]
summary["C.Out"] = summary["Clock_Out"] / summary["Count_Day"]
summary["Late"] = summary["Late_Count"] / summary["Count_Day"]

summary = summary.fillna(0)

KeyError: "Label(s) ['Count Day'] do not exist"